### ISSUE TITLE
Contact?

### ISSUE THREAD

**Issue by angelfor3v3r** [bleonars/dx11-renderer#3]
Is there a way I can contact you about your previous repo? Thanks.

**Comment by bleonars** [comment]
Sorry, I was unaware of the code similarity you mentioned. Most of the code I received from a friend which gave me permission to post it. This was years ago... I thought I could trust that and was not aware that this was something you wrote (not sure how he obtained it). I have since deleted the repo. Sorry for the misunderstanding.

**Comment by bleonars** [comment]
Like I said, this was years ago and I do not think that individual is tied to you/yazzn directly as he claimed to be Russian if I recall correctly. We met online, so I don't know much about him/her. We are no longer associated. Maybe the code was passed on? Anyways, I'm glad this could be smoothly resolved. Sorry for the inconvenience!
